version: '3'
services:
  bitcoind:
    image: seegno/bitcoind
    restart: unless-stopped
    ports:
      ## Comment these if they conflict with something else you're running.
      #-- Mainnet
      - "8333:8333"
      - "8332:8332" # RPC
      #-- Testnet
      - "18333:18333"
      - "18332:18332" # RPC
    command:
      -printtoconsole
      -regtest=1
      -rest
      -rpcallowip=10.211.0.0/16
      -rpcallowip=172.17.0.0/16
      -rpcallowip=192.168.0.0/16
      -rpcallowip=0.0.0.0/0
      -rpcuser=foo
      -rpcpassword=bar
      -rpcport=18332
      -server
      -zmqpubrawblock='tcp://127.0.0.1:288332'
      -zmqpubrawtx='tcp://127.0.0.1:288332'
  bcoin:
    image: purse/bcoin
    restart: unless-stopped
    env_file:
      - ./bcoin.env
    ports:
      # Regtest
      - "48444:48444"
      - "48332:48332" # RPC
      - "48334:48334" # Wallet
      # Simnet
      - "18555:18555"
      - "18556:18556" # RPC
      - "18558:18558" # Wallet
  db:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
  bws:
    image: joemphilips/bws
    links:
      - db
    ports:
      - "3232:3232"
      - "3231:3231"
      - "3380:3380" # for message notification
      - "443:443"
