version: '2'
services:
  bitcoind:
    extends:
      file: docker-compose.dependency.yml
      service: bitcoind
  bcoin:
    extends:
      file: docker-compose.dependency.yml
      service: bcoin
  walletts:
    environment:
      - CI=1 # since ora will cause error without this
    build:
      context: .
      dockerfile: Dockerfile.test
    command: yarn test:docker-integration
    depends_on:
      - bcoin
      - bitcoind
