jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: apt install -y yarn
      - run:
          command: yarn bootstrap
          name: bootstrap
      - run: 
          command: yarn test
          name: test
version: 2
