jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: ./.circleci/install_yarn.sh
          name: install yarn
      - run:
          command: yarn && yarn bootstrap
          name: bootstrap
      - run:
          command: yarn build
          name: build
      - run:
          command: yarn test
dependencies:
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn
test:
  override:
    - yarn test

version: 2
