jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: ./.circleci/install_yarn.sh && ./.yarn/bin/yarn
          name: install yarn
      - run:
          command: ./.yarn/bin/yarn bootstrap
          name: bootstrap
      - run:
          command: ./.yarn/bin/yarn build
          name: build
      - run:
          command: ./.yarn/bin/yarn test
          name: test
version: 2
