jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          command: ./.circleci/install_yarn.sh
          name: install yarn
      - run:
          command: [ -s "/opt/circleci/.nvm/nvm.sh" ] && . "/opt/circleci/.nvm/nvm.sh"
      - run:
          command: yarn && yarn bootstrap
          name: bootstrap
      - run:
          command: yarn build
          name: build
      - run:
          command: yarn test
version: 2
